# .github/workflows/tests.yml
name: Tests
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: get source code
      uses: actions/checkout@v2
    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
        cache: 'pip' # caching pip dependencies
        cache-dependency-path: |
          **/requirements*
        architecture: x64
    - run: make setup-venv
    - run: make checks
    - run: bash <(curl -s https://codecov.io/bash)
